### ISSUE TITLE
Add support for the Razer Chroma Kitty Edition

### ISSUE THREAD

**Issue by Sirmentio** [z3ntu/RazerGenie#110]
Hello, I'm using this and Razer Genie doesn't seem to support my headset. There's no icon for it, and the custom layout editor isn't available. Here's a picture of the device:
![image](https://user-images.githubusercontent.com/42724159/110158932-02d68600-7db8-11eb-9922-5c45e5d52bbb.png)

**Comment by z3ntu** [comment]
Hi sorry for the late answer. The custom layout editor is a relatively minor feature - if you want something quite similar but not as polished you can build RazerGenie with this option enabled https://github.com/z3ntu/RazerGenie/blob/master/meson_options.txt#L1

The device picture was fixed with v3.0.1 which you should already have installed: https://github.com/openrazer/openrazer/commit/b0241f17975e5f067ac424c80d90ea3082850dd2

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!
