### ISSUE TITLE
customeditor errors

### ISSUE THREAD

**Issue by TheShin21** [z3ntu/RazerGenie#137]
Hello,
I have a "Razer Huntsman V2 Analog" keyboard and tried to use RazerGenie to change my actuation points and profiles, however that doesn't seem to be shown anywhere in the software and clicking on the customeditor button simply spits out 3 errors. I have Openrazer installed and have made sure that it works.

![2022-07-23_11-34](https://user-images.githubusercontent.com/39313087/180599786-24483a70-1c41-4cac-aaa9-e8e5e02e0478.png)
![2022-07-23_11-34_1](https://user-images.githubusercontent.com/39313087/180599788-71e71f30-e0e9-4112-b1c2-fc319be4ed6a.png)
![2022-07-23_11-35](https://user-images.githubusercontent.com/39313087/180599790-60b8979b-45a3-4493-8047-01ed5c5fd759.png)

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!

**Comment by gardotd426** [comment]
@z3ntu I am considering buying this keyboard, just FYI it's the same as a regular Huntsman V2 as far as the layout is concerned. I've never used OpenRazer/RazerGenie before (I'm on a Corsair right now so I use ckb-next) so I'm a bit confused as to how you'd use the custom layout editor to change actuation points, but that's the real issue here: the Huntsman V2 Analog has optical analog switches (which is huge), and so unless there's a way to modify this in the customeditor (?) then it would need to be supported in the GUI, I mean really all it would take is a slider for the actuation point of each key, and all it would take is finding out the mm range of actuation points that the Huntsman V2 Analog supports. If you'd be willing to wire up the GUI I could get you the data on what ranges it supports and whether the Analog actuation point is customizable *per*-key or all-key.

**Comment by z3ntu** [comment]
@gardotd426 There's no support for the "analog" part of that keyboard yet, see https://github.com/openrazer/openrazer/issues/1579 . The "custom editor" in RazerGenie is just for setting color on each individual key.

Also please don't comment on random closed issues, thanks.
