### ISSUE TITLE
FR: display battery level

### ISSUE THREAD

**Issue by Zahrun** [z3ntu/RazerGenie#163]
Would like to be able to see the battery level for my Viper V2 Pro in RazerGenie.

**Comment by z3ntu** [comment]
Definitely planned! If you have an idea (or a mockup) how you would imagine the battery % to be displayed in the UI, please feel free to tell me. I'm having a hard time figuring out a UI that works for that ;)

**Comment by Zahrun** [comment]
1. I think it would be nice to have the battery level for each device on the left-side panel with all the devices (9%) so that we can see all battery levels in one glance. The battery level could be put under the name of the device, or the name of the device could go above the icon and the battery status goes under the icon. It is also fine to not have that, if you don’t want to clutter the device list.
2. I think in the top-right corner of the device page, there is a blank space that can be used to show the battery level (42%)
3. In the list of the options, we could also have a section with information about the battery, which could have a more visual indicator of battery level and whatever information we want to display about the battery (79%)
4. At the bottom, above the serial number could also be a line for the battery status, but maybe the point of these small lines are to show less dynamic information
![mockup](https://github.com/z3ntu/RazerGenie/assets/10415894/c216ba84-1abd-4cd7-bf51-1a43ad40d87f)

**Comment by TriMoon** [comment]
> 1. It is also fine to not have that, if you don’t want to clutter the device list.

That would be a shame to not have...

**Comment by L0Lock** [comment]
Kind of related, let me know if I should open a different ticket for it:

Could we have a different lighting state for devices that can be either plugged / on battery?

I have a wireless Razer Viper Ultimate. On Windows, the Razer Synapse software allows choosing a different lights animation for when the device is charging, and both plugged/battery settings are different by default. So that you know very easily whether your device is charging or not with no delay, unlike the software's display that can take a few more seconds to update and requires extra steps to open in the first place.

**Comment by z3ntu** [comment]
> Could we have a different lighting state for devices that can be either plugged / on battery?

I'm not aware of this being a hardware feature, so that would require user space to be polling the device for charging status and applying a new effect when it detects that it's charging / not charging. Not sure where this would fit into the stack - for now you can write your own (e.g. Python) script that does essentially what I described, so poll charging status and set the effects you want when it's either charging or not charging.

**Comment by z3ntu** [comment]
Got something now for battery percent & charging status, not particularly pretty but it does the job :) 

![image](https://github.com/z3ntu/RazerGenie/assets/3768500/14573318-a284-42ea-b7b2-56b2d33055b5)

It's currently not refreshing automatically yet, so probably needs to re-open the app to update the percentage, I've got it planned to refresh the values on a timer.

**Comment by Zahrun** [comment]
Great, thank you
