### ISSUE TITLE
RazerGenie doesn't see my Deathstalker V2 Pro TKL

### ISSUE THREAD

**Issue by JaCh0o** [z3ntu/RazerGenie#164]
Hello,
Is it something with my PC or it's not compatible yet with Deathstalker V2 TKL ?

**Comment by z3ntu** [comment]
Answered in the OpenRazer chat, let's continue there

**Comment by JaCh0o** [comment]
FOR INFORMATION:
I got an answer on the Official Telegram OpenRazer channel that currently OpenRazer deamon doesn't support more than one device from one Razer dongle, therefore if any of you are connecting Razer wireless devices such as keyboards or mices through one USB dongle you won't have the ability to control it thru RazerGenie nor OpenRazer apps.

And here is question because I guess most of us are using one dongle to control both devices through one dongle when will it be supported and even is it possible ?

**Comment by z3ntu** [comment]
Not sure this is tracked anywhere in the openrazer repo, maybe you can already fine an open issue regarding this.

But with the current architecture of OpenRazer I don't see a quick fix being possible here, too much of it is just bound to having a separate USB device per input device.

I'm closing this though since it's not a problem with RazerGenie but more an unsupported use case inside OpenRazer.
