### ISSUE TITLE
Synchronize Effects not working

### ISSUE THREAD

**Issue by baanaan** [z3ntu/RazerGenie#53]
Nice Software over all! 
The option synchronize effects isn't working properly 
or is the effect that my devices pulsate after each other? :D 
My Devices:
BlackWidow Ultimate 2013
Razer DeathAdder Elite

**Comment by nightsky30** [comment]
This may be what I identified and fixed in the openrazer daemon with my test branch in the following commits:

https://github.com/nightsky30/openrazer/commit/d7ce2d9d7bbf69dba152a449062efbf02c91b6dd
https://github.com/nightsky30/openrazer/commit/230ce8cc141d79e6c3dc469c0035b98f71de9d97

I can't create a PR for that branch at the moment as I'm waiting on a PR I had created that exists in master.  Do the descriptions sound similar?

**Comment by z3ntu** [comment]
Effect sync has improved quite a bit since 2019, this should be resolved. Closing.
