### ISSUE TITLE
Add ability to change device mode for mouse

### ISSUE THREAD

**Issue by HenryJk** [z3ntu/RazerGenie#65]
This capability on openrazer itself is possible [here](https://github.com/openrazer/openrazer/wiki/Using-the-mouse-driver#device_mode---set-device-mode). The primary reason is that during gaming session sometimes changing dpi is an unwanted feature as misclick happen. Setting the mouse to driver mode will disable the dpi button and stopping accidental dpi change from happening.

**Comment by z3ntu** [comment]
The DPI buttons stopping to work is more of a side effect rather than intended feature :wink: 
For now using a script to write to the file in sysfs is probably your easiest solution. Theoretically if the device is in "device mode" or "driver mode" should be transparent to everyone because the daemon should handle that.

**Comment by z3ntu** [comment]
Closing as implementing this is not in scope, device mode should completely be handled by OpenRazer itself without being touched from outside.
