### ISSUE TITLE
Razer Huntsman Elite Matrix Mapping

### ISSUE THREAD

**Issue by Riku5543** [z3ntu/RazerGenie#67]
Hey! I put this in an issue comment, but thought it might be better to post a new issue instead. Below, I've attached the matrix mappings for this keyboard. It uses the en_US layout and has a 9 22 matrix. Here you go!
[Razer Huntsman Color Mapping.txt](https://github.com/z3ntu/RazerGenie/files/4106843/Razer.Huntsman.Color.Mapping.txt)

**Comment by z3ntu** [comment]
Thanks for the file! I'll see what I can do with this unusual device :)

**Comment by Develon5543** [comment]
No problem! If you have any questions, let me know.

**Comment by toluschr** [comment]
I'd also appreciate support for this device.

**Comment by toluschr** [comment]
I'm currently working on the layout. Still needs some work. I'll send a patch when I'm done.
![13:22:57](https://user-images.githubusercontent.com/44272603/81806582-f299a580-951c-11ea-9f12-fa89bdc10e48.png)

**Comment by toluschr** [comment]
@Develon5543 do you mind trying this? https://gist.github.com/toluschr/cacdea6068d313b8c452515d02bc5ca3

**Comment by Develon5543** [comment]
Yes I'll try it when I can. Thank you
________________________________

**Comment by z3ntu** [comment]
@toluschr @Develon5543 Any update on that?

**Comment by Develon5543** [comment]
I tried applying the patch to master, but I don't think I did it 100% correctly. Here's what I did:
`patch -i 001-add-huntsmanelite-layout.patch`
This resulted in me doing some manual changes, like creating the `razerhuntsmanelite.json` file. I also had to manually change data/build.json to add the Huntsman Elite lines. So the resulting issue is probably because the patch wasn't used properly.

After patching, my keyboard shows up in the program and I can change to the default presets just fine. When clicking on the custom editor button, this shows up in the terminal.
```
Dimensions: 9 22
"RazerGenie: Using the development razerhuntsmanelite.json file."
```
However, the program still says that my layout (en_US) isn't supported, and it also can't find the german one or any other layout either.

**Comment by z3ntu** [comment]
@Develon5543 On master you need to use labels such as `"US"` instead of `"en_US"` . It's possible that the error message doesn't reflect that yet.

**Comment by Develon5543** [comment]
Ah. Seems the patch didn't include support for US. Changing German to US in `razerhuntsmanelite.json` causes the menu to show up properly. I took a screenshot of the layout menu after testing all of the options. The green ones are correct but could have incorrect labels and the red ones don't exist in this layout. There are 2 red keys, but only 1 missing light on the keyboard. (backslash/pipe)
I could probably fix this on my own. I'll see what I can do
![2020-10-02_12-10](https://user-images.githubusercontent.com/53382296/94960869-72161a00-04a8-11eb-948d-afee9d85e028.png)

**Comment by Develon5543** [comment]
[Here](https://pastebin.com/Zyy0udeK) is a link to an updated razerhuntsmanelite.json, made for a US layout. The formatting could use improvements, but it's good in a pinch. All of the keys work properly. All you have to do is apply the patch above and then overwrite the json file with this one in order to get US support.

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!
